spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@192.168.22.123:13_lina/config-springcloud.git
          username: 15831687415@163.com
          password: wo13784207239
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083

