eureka:
  client:
    service-url:
       defaultZone: http://localhost:8762/eureka/

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.255.129:3306/order?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true

#  rabbitmq:
#    host: http://192.168.255.129
#    port: 5672
#    username: guest
#    password: guest

